# Generated by Django 3.2 on 2021-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/nachovidondo/Python/Pet/PetAdoption/AdoptionResponsable/Imagenes/avatar1.png', upload_to='avatars/'),
        ),
    ]
