# Generated by Django 3.2 on 2021-05-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('race', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raza')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('date_found', models.DateField(blank=True, null=True, verbose_name='Fecha de encuentro')),
                ('place_found', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar encontrado')),
                ('looking_for_owner', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=200, null=True, verbose_name='Busca Dueño')),
                ('treatments', models.TextField(blank=True, null=True, verbose_name='Tratamientos')),
                ('treatments_cost', models.FloatField(blank=True, null=True, verbose_name='Gastos de Tratamientos')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono de Contacto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagenes')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Creacion')),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='PetImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pet')),
            ],
            options={
                'verbose_name': 'Agregar una Imagen',
                'verbose_name_plural': 'Agregar mas Imagenes',
            },
        ),
    ]
