# Generated by Django 3.1.7 on 2021-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('race', models.CharField(max_length=200, verbose_name='Raza')),
                ('description', models.CharField(max_length=400, verbose_name='Descripcion')),
                ('date_found', models.DateField(verbose_name='Fecha de encuentro')),
                ('place_found', models.DateField(verbose_name='Lugar encontrado')),
                ('looking_for_owner', models.BooleanField(default=True, verbose_name='Busca Dueño')),
                ('treatments', models.CharField(max_length=300, verbose_name='Tratamientos')),
                ('treatments_cost', models.FloatField(verbose_name='Gastos de Tratamientos')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefono de Contacto')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagenes')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
