# Generated by Django 3.1.7 on 2021-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_auto_20210331_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='place_found',
            field=models.CharField(max_length=200, verbose_name='Lugar encontrado'),
        ),
    ]
