# Generated by Django 3.1.7 on 2021-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0003_auto_20210331_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='looking_for_owner',
            field=models.BooleanField(choices=[('Si', 'Si'), ('No', 'No')], verbose_name='Busca Dueño'),
        ),
    ]
