# Generated by Django 3.1.7 on 2021-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0005_auto_20210331_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='looking_for_owner',
            field=models.BooleanField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', null=True, verbose_name='Busca Dueño'),
        ),
    ]
