# Generated by Django 3.1.7 on 2021-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0006_auto_20210331_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='looking_for_owner',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=200, null=True, verbose_name='Busca Dueño'),
        ),
    ]
