# Generated by Django 3.1.7 on 2021-04-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0007_auto_20210331_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pet')),
            ],
            options={
                'verbose_name': 'Agregar una Imagen',
                'verbose_name_plural': 'Agregar mas Imagenes',
            },
        ),
    ]
