# Generated by Django 3.2 on 2021-05-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_linked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='linked',
            new_name='liked',
        ),
    ]
