# Generated by Django 3.2 on 2021-05-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtitulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagenes')),
            ],
            options={
                'verbose_name': 'Index',
            },
        ),
        migrations.CreateModel(
            name='IndexImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('index', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Index.index')),
            ],
            options={
                'verbose_name': 'Agregar una Imagen',
                'verbose_name_plural': 'Agregar mas Imagenes',
            },
        ),
    ]
